language: python
python: '3.6'
cache: pip

env:
  global:
    - AWS_DEFAULT_REGION: us-east-1

install:
  - "bash -x ./scripts/install_deps.sh"

script:
  - pytest tests
  - "bash -x ./scripts/lint_code.sh"
  - "bash -x ./scripts/lint_cfn.sh"
