language: python
python: '3.6'
cache: pip

env:
  global:
    - AWS_DEFAULT_REGION: us-east-1

install:
  - find . -name 'requirements*.txt' -exec pip install -r '{}' \;

script:
  - pytest tests
  - "bash -x ./scripts/lint_code.sh"
