version: 0.2

env:
  variables:
    # ARTIFACTS_BUCKET is also available, coming from pipeline.yml
    PIP_CACHE: pip_cache

phases:
  install:
    commands:
      - printenv
      - python --version && pip --version
      - scripts/install_deps.sh
      - pip list

  pre_build:
    commands:
      - pytest tests
      - scripts/lint_py.sh
      - scripts/lint_cfn.sh

  build:
    commands:
      - scripts/build.sh

  post_build:
    commands:
      - aws cloudformation package --template-file infrastructure/functions.yml --output-template-file packaged_functions.yml --s3-bucket "${ARTIFACTS_BUCKET}"
      - python scripts/sam_translate.py --input-file packaged_functions.yml --output-file cfn_functions.json

artifacts:
  files:
    - cfn_functions.json

cache:
  paths:
    - pip_cache
